# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
